### ISSUE TITLE
No newline for code output

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/hugodown#106]
The following document renders differently after version 0.4.0.

````r
---
output: hugodown::hugo_document
---

```{r}
1 + 1
```
````

It used to render to

````html
---
output: hugodown::hugo_document
rmd_hash: afe01a4d6eaaf4f6

---

<div class="highlight">

<pre class='chroma'><code class='language-r' data-lang='r'><span class='m'>1</span> <span class='o'>+</span> <span class='m'>1</span>
<span class='c'>#&gt; [1] 2</span></code></pre>

</div>
````

Which looks like this

![Screen Shot 2022-07-14 at 10 47 04 AM](https://user-images.githubusercontent.com/14034784/179049995-938fef77-5381-4cd2-b866-52f662ae8cfb.png)

It now renders to

````html
---
output: hugodown::hugo_document
rmd_hash: afe01a4d6eaaf4f6

---

<div class="highlight">

<pre class='chroma'><code class='language-r' data-lang='r'><span><span class='m'>1</span> <span class='o'>+</span> <span class='m'>1</span></span><span><span class='c'>#&gt; [1] 2</span></span></code></pre>

</div>
````

Which gives the following output

![Screen Shot 2022-07-14 at 10 47 00 AM](https://user-images.githubusercontent.com/14034784/179049677-0769a898-0138-4a33-9ac1-ca4f75c40a22.png)

**Comment by hadley** [comment]
This also explains why this failure wasn't causing widespread problems — a downlit problem would affect every pkgdown website, but a hugodown issue only affects the small number of hugodown users (and only those who had installed relatively recently)
