### ISSUE TITLE
Allow local site preview of future dated or draft posts

### ISSUE THREAD

**Issue by apreshill** [r-lib/hugodown#15]
Hugo has a way to preview the site locally, and this method typically shows all future dated posts and those with `draft: TRUE` in the YAML.

See docs here:
https://gohugo.io/getting-started/usage/#draft-future-and-expired-content

With hugodown, using the combination of `server_start()` and knitting to `hugodown::hugo_document()`, I'm unable to preview any draft or future content locally.

blogdown's docs on this:
https://bookdown.org/yihui/blogdown/local-preview.html

**Comment by hadley** [comment]
I also encountered this approximately 15 minutes ago so it's now fixed 😄
