### ISSUE TITLE
Feature request: blogdown2hugodown

### ISSUE THREAD

**Issue by njtierney** [r-lib/hugodown#16]
Would there be scope to help transition from blogdown to hugodown, à la `roxygen2md::roxygen2md()`?

**Comment by hadley** [comment]
See https://github.com/r-lib/hugodown#converting-from-blogdown; there should be relatively little work to do.

**Comment by hadley** [comment]
(Let me know if that's not enough info, or if there's anything else you need to do so I can improve it)

**Comment by njtierney** [comment]
It worked! :tada:

I think a few clarifications could be really helpful.

[Configuration](https://github.com/r-lib/hugodown#configuration)

- Could it name which file to edit? I believe we want this to be the `config.toml` file in the main directory ([here in my website](https://github.com/rbind/njtierney.com/blob/0dc8299c105ddfb47dd1c71411616a220ff66292/config.toml#L14)

- [converting from blogdown](https://github.com/r-lib/hugodown#converting-from-blogdown)
  - Perhaps linking to the archetype being in the `theme` folder - I think you're referring to [this file?](https://github.com/tidyverse/tidyverse.org/blob/master/themes/hugo-tourmaline/archetypes/blog/index.Rmd)

FWIW, here is the hugodown changes that I made: https://github.com/rbind/njtierney.com/pull/32
