### ISSUE TITLE
Preserving authors as a vector?

### ISSUE THREAD

**Issue by maelle** [r-lib/hugodown#18]
At the moment knitting my Rmd that has

```
authors:
  - Maëlle Salmon
```

gives 

```
authors: Maëlle Salmon
```

I'd understand your closing this since [I should make the theme robust to this change](https://github.com/rstudio/blogdown/pull/435#pullrequestreview-369664310)

**Comment by hadley** [comment]
No, this is a buglet with my yaml roundtripping that I don't know how to work around yet.

**Comment by maelle** [comment]
do you need the roundtripping only for adding the hash? I was thinking of a non elegant solution, replacing

```
---
```

with

```
hash blabla
---
```

using regex (with another case when the hash exists). `rmarkdown` uses regex to identify the YAML.

**Comment by maelle** [comment]
Thanks to this issue I'm realizing [`tinkr`](https://github.com/ropenscilabs/tinkr) (commonmark and xlst instead of pandoc) probably doesn't handle the YAML roundtripping much better. :upside_down_face:

**Comment by hadley** [comment]
@maelle yeah, that's what I was thinking about doing

**Comment by cderv** [comment]
I wondered the same for this yaml preservation. 

Just in case you don't know, there is currently an internal rmarkdown fonction to extract yaml without parsing it : [`partition_yaml_front_matter`](https://github.com/rstudio/rmarkdown/blob/98f83c855ae40953f3bd82620916610238641653/R/output_format.R#L692)

It is used to preserve the yaml in `md_document` format, and internally in `yaml_front_matter`. Exporting this function could be a solution maybe if you want to reduce rewritten function. 
`extract_yaml` is simple enough though so...

**Comment by hadley** [comment]
Yeah I read the source to that and extracted the bit I thought was sufficient.
