### ISSUE TITLE
hugo_document rendering is very long when hugo server is not started.

### ISSUE THREAD

**Issue by cderv** [r-lib/hugodown#20]
While testing the new `hugo_document`  format, I observe a very long rendering time for very simple document when the hugo server is not started. 

I isolate the issue to be with the post processing part and specifically the active port checking. 
I takes a whole minute of real time.
``` r
bench::system_time(hugodown:::port_active(1313L))
#> process    real 
#>  62.5ms   1.02m
```

This is obviously due to the try with  `socketConnection`. There is a timeout that default to `getOption("timeout")` which is 60. see `?socketConnection`

If I change the option to like 5 second, it is more quicker... 5 sec. 
``` r
withr::with_options(list(timeout = 5), 
                    bench::system_time(hugodown:::port_active(1313L)))
#> process    real 
#> 78.12ms   5.07s
```

Maybe for a smoother user experience there could be smaller timeout set in hugodown to prevent this happening when the server is not started. 

Let's not that when the hugo server is started, it takes less than 1s to check, so rendering Rmd file is as usual.

**Comment by hadley** [comment]
Are you on windows? (It's basically instant for me)

**Comment by cderv** [comment]
Yes I am on windows 10.

**Comment by cderv** [comment]
Did you try with R 4.0.0  ? 

It seems this is a bug fix. See https://cran.r-project.org/doc/manuals/r-devel/NEWS.html
> socketConnection(server = FALSE) now respects the connection timeout also on Linux.

**Comment by cderv** [comment]
No. I tested with rocker with 4.0.0 and it is also an error instantly on linux. 

However, I see also in the NEWS
> socketConnection(server = FALSE) now returns instantly also on Windows when connection failure is signalled.

Previously I was in 3.6.3 on windows. I updated to 4.0.0 and now this is better
``` r
# still the same value
getOption("timeout")
#> [1] 60
# but way faster
bench::system_time(hugodown:::port_active(1313))
#> process    real 
#>  62.5ms   2.07s
```

<sup>Created on 2020-05-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cderv** [comment]
Thanks ! This is quicker to render now. It helps !
