### ISSUE TITLE
Config vignette

### ISSUE THREAD

**Issue by hadley** [r-lib/hugodown#30]
* Required components in hugo config (extracted from readme)
* Optional components in `_hugodown.yaml`

**Comment by maelle** [comment]
Reg `_hugodown.yaml`, should https://ymlthis.r-lib.org/articles/yaml-fieldguide.html mention it

**Comment by hadley** [comment]
@maelle I think it's a bit premature to refer to hugodown anywhere external since it's still very much in flux. I'd wait for the first CRAN release.
