### ISSUE TITLE
Vignette on post workflows?

### ISSUE THREAD

**Issue by maelle** [r-lib/hugodown#31]
Not a very original idea. :grin:

I really like

* https://rstudio.github.io/distill/blog_workflow.html (since Hugo has drafts too, there are two common possibilities, using drafts, and using git branches)

* https://twitter.com/apreshill/status/1108005028067835904

* https://www.garrickadenbuie.com/blog/blogdown-netlify-new-post-workflow/

**Comment by hadley** [comment]
I think there's only really two deployment workflows worth doing/describing:

* For single author/low stakes blogs, I think it's easiest to preview/check locally, commit and then have a GitHub action deploy your blog to github pages

* For multiple author/high stakes blogs, each post should be a PR and you deploy with netlify.

**Comment by maelle** [comment]
In any case another suggestion: the option to not build future posts and saying that if one sets up a daily build then that can help schedule posts.

**Comment by hadley** [comment]
But then you need to set up some sort of cron job to ensure that the site is rebuilt each day?

**Comment by maelle** [comment]
Yes, It's what I meant with setting up a daily build. 🙂 It might be a small idea at the end of a vignette "What if I want to schedule posts" -- less important than other aspects but good to know. There's a Zapier zap for daily Netlify deploys, alternatively one can use GitHub Actions. 

Now that I think of it maybe another vignette "Advanced/fancy setups for your website" might be where to collect such niche examples (also Jim's blogdown website with the daily build on GHA updating the nice timeline on the homepage; [Noam Ross' Hugo website with a daily Circle CI build getting data from ORCID](https://github.com/noamross/noamross.net/blob/master/.circleci/config.yml)). But ensuring the examples such a vignette might link are not broken might be too much work vs usefulness of the vignette.

**Comment by apreshill** [comment]
Tangentially related to workflows, I would love to teach with and use some usethis style functions for:

+ setting up GH actions (maybe [this function](https://usethis.r-lib.org/reference/github_actions.html) could have a project type argument where you could specify hugodown) and 
+ using Netlify (to set up the [netlify.toml file](https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/)).

If either of these are in scope for hugodown, I can move this to a separate issue rather than hijacking this one 😉

**Comment by hadley** [comment]
Yes, they're definitely in scope 😄

**Comment by hadley** [comment]
Now I'm wondering whether it's worthwhile to explain github actions + github pages — yes, it eliminates one (free) service, but it adds a lot of extra complexity and you don't get deploy previews.

**Comment by maelle** [comment]
In distill docs, _many_ possibilities are documented: https://rstudio.github.io/distill/publish_website.html

**Comment by hadley** [comment]
I'll keep working on the deploy vignette, but it's likely to remain focussed on netlify + connect. I think I'd accept a PR that described how to use GitHub actions, but I think it would need to be paired with a helper function that created a useful workflow.
