### ISSUE TITLE
Addin for post creation?

### ISSUE THREAD

**Issue by maelle** [r-lib/hugodown#33]
* blogdown New Post Addin is really nice when your theme is compatible (e.g. uses authors, not author)

* ymlthis also has an addin.

Differences with `new_post()`

* ymlthis and blogdown use whoami for the full name. usethis full name could still be prioritary but then whoami is a good guess and doesn't require configuration.

* blogdown addin loads existing tags and one can create new tags.

* blogdown addin lets you choose from several archetypes (e.g. if you have one for Rmd and one for md)

* having an user-friendly interface :-)

**Comment by hadley** [comment]
TBH I really don't like the add-in, and much prefer the code based system. I think most of the issues you point out could be resolved without an add-in:

* I forgot about `whoami::fullname()`, so I could definitely use that
* Ok, I can't do this one
* `new_post()` does that automatically based on the directory (i.e. just like hugo)
* Given that you have to edit the yaml by hand anyway, I don't think it's a hug advantage

**Comment by maelle** [comment]
Right, setups with different archetypes for the same directory are probably not the norm. :-) I'm not sure about addin vs code (whether it's more usual to prefer one or the other) but what's sure is that it's probably a lot of maintenance work.

> I forgot about whoami::fullname(), so I could definitely use that

:tada:
