### ISSUE TITLE
Code/Chunk output HTML structure differs from hugo/goldmark

### ISSUE THREAD

**Issue by jemus42** [r-lib/hugodown#35]
I am currently experimenting to see if I can easily switch from blogdown + `.Rmarkdown` to hugodown, and so far the first "issue" I have found is the chunk output.

I have prepared an [example hugo blog repo](https://github.com/jemus42/hugodown-testing) using the same theme I'm using for my blog without any CSS / layout modifications. It's auto-deployed to netlify at https://hugodown-testing.netlify.app/

I have started two blog posts, one using hugo+goldmark, and one using hugodown:
- Plain Markdown post: https://hugodown-testing.netlify.app/plain-markdown/
- Rmd post: https://hugodown-testing.netlify.app/hugodown-rmarkdown/

## Code output

I am assuming that the output of `hugodown_document` is intended to be as close to that of hugo/goldmark as possible, but where in the plain markdown / goldmark post, a code chunk looks like this:
![image](https://user-images.githubusercontent.com/1613346/83946677-9f143200-a812-11ea-889f-1286460911cc.png)
where code is contained in two nested `<div>`s:
![image](https://user-images.githubusercontent.com/1613346/83946713-d7b40b80-a812-11ea-8c41-05ee9a077b84.png)

…hugodown however produces this output:
![image](https://user-images.githubusercontent.com/1613346/83946742-fadebb00-a812-11ea-9fa8-862ffae421dc.png)
where the entire chunk is wrapped in `<pre class="chroma">`.

This leads to issues regarding the styling (margins, border-radius, probably why the colors differ?) in this particular theme, but I appreciate that this might not be a problem at all when using different themes (or using extra CSS).  

I hope it's possible to adjust this without having to account for site-specific goldmark settings (like line numbers and tabular display in my case).  
I would still like a solution where hugodown outputs code to a hugo `highlight` shortcode, but I assume that's not possible when downlit does the auto-linking / highlighting (which is very cool, I just tend to want to over-customize, and shortcodes give me a lot of flexibility across md + Rmd).

## Plot output 

Related to this are code chunks with plot output ([live example](https://hugodown-testing.netlify.app/hugodown-rmarkdown/#plots)):

![image](https://user-images.githubusercontent.com/1613346/83946806-5c068e80-a813-11ea-8c32-3417b62f8ad1.png)

Here the output figure is still contained in the above `<pre>`, causing the "code background color" — I assume this is not by design for some auto-linking/downlit-reason? If so, is there a way I can avoid this behavior?

**Comment by jemus42** [comment]
Related to the second part regarding the entire chunk being wrapped in `<pre>`: This also affects chunks that output markdown, e.g. via `knitr::kable`:
https://hugodown-testing.netlify.app/posts/rmarkdown-content/#table

![image](https://user-images.githubusercontent.com/1613346/83949391-cf180100-a823-11ea-9d8c-7ebb6ea76b79.png)

**Comment by hadley** [comment]
@jemus42 would you mind using (the just added `hugo_build()` to render the site so that you can commit the html files and link to them? That's easier for me to work with than screenshots of the html.

**Comment by hadley** [comment]
(It's not super important here since I know what the problem is, but it generally will make life easier for me

**Comment by jemus42** [comment]
Oh, sure thing! Sorry, I thought linking to the live HTML via netlify would be enough, but I see your point.

- [hugodown post HTML](https://github.com/jemus42/hugodown-testing/blob/master/public/hugodown-rmarkdown/index.html)
- [plain markdown post HTML](https://github.com/jemus42/hugodown-testing/blob/master/public/plain-markdown/index.html)

Thanks!

**Comment by hadley** [comment]
This looks like a `pre` to me: https://github.com/jemus42/hugodown-testing/blob/master/public/plain-markdown/index.html#L148-L158. What am I missing?

**Comment by hadley** [comment]
The colours differ because:

* chroma is (IMO) incorrectly marking the `=` in function calls as an operator.
* downlit [doesn't currently](https://github.com/r-lib/downlit/issues/12) distinguish between logical and numeric constants

**Comment by jemus42** [comment]
That `<pre>` is what I would call the "inner" bit – but it is nested inside two divs https://github.com/jemus42/hugodown-testing/blob/master/public/plain-markdown/index.html#L133

As for the color difference: Thanks for clearing that up :)

**Comment by jemus42** [comment]
(Please let me know if I should disable the "code in table with line numbers" setting as this might make it needlessly complex, but my local testing shows that without line numbers, the structure is still similiar):

```html
<div class="highlight">
  <pre class="chroma">
    <code class="language-r" data-lang="r">
      (...)
    </code>
   </pre>
</div>
```

**Comment by hadley** [comment]
Hmmm, this is going to be fiddly to do well, since the design of the knit hooks isn't quite flexible enough. Ideally the `chunk` hook would wrap in the `<div class="highlight"><div class="chroma">`, and then runs of code + raw output/message/warning/error would be collapsed into a single `<pre class="chroma"><code ...>`. 

Possible options:

* Just accept the html will be a little ugly and have each code/output/message/... output a single 
`<pre>` — but this will probably to produce unwanted margins.

* Previous option but with regular expression to collapse runs 😬 

* Maintain a separate data structure outside of knitr, so and use that in the `chunk` hook, rather than working with its input (since knitr [pastes into a single string](https://github.com/yihui/knitr/blame/master/R/block.R#L266-L268)) — that would eliminate a lot of other knitr customisations, but might be ok.

**Comment by hadley** [comment]
Oh I realised there's a simpler compromise — we just maintain external state recording whether or not we're currently in a code block.

**Comment by hadley** [comment]
Hmmm, that doesn't quite work because asis output doesn't appear to go through any output hooks 😬

**Comment by hadley** [comment]
@jemus42 I think that should fix it; if you encounter more/new problems please file a new issue 😄
