### ISSUE TITLE
Background color and image resolution for R figure output (CSS)

### ISSUE THREAD

**Issue by apreshill** [r-lib/hugodown#38]
Noticing background colors around figure output:

<img width="1237" alt="Screen Shot 2020-06-08 at 8 16 12 AM" src="https://user-images.githubusercontent.com/12160301/84049501-5f0f9500-a961-11ea-88a6-16410e35f339.png">

I suspect it may have to do with the CSS Chroma additions? They go away when I remove the following CSS background colors:

```
pre {
	margin: 0 0 1rem 0;
	/* background-color: #f8f8f8; */
	border-color: #f8f8f8;
	font-size: 0.7rem;
	border-radius: 4px;
}
pre, code {
	font-family: "Roboto Mono", monospace;
	color: #c7254e;
	/* background-color: #f9f2f4; */
}
```

<img width="1237" alt="Screen Shot 2020-06-08 at 8 16 34 AM" src="https://user-images.githubusercontent.com/12160301/84049574-764e8280-a961-11ea-8f4b-546bc55bc2a5.png">

Also noticing that the figure resolution with hugodown rendering is not good. A fresh Academic site via blogdown shows much crisper figures (and no background color):

<img width="1237" alt="Screen Shot 2020-06-08 at 8 31 28 AM" src="https://user-images.githubusercontent.com/12160301/84050424-92065880-a962-11ea-9646-b6d1842a1460.png">

**Comment by njtierney** [comment]
I noticed that my figures improved in quality changing `fig.retina = 2`, but that might be irrelevant in this case.

**Comment by apreshill** [comment]
That is it- I would do that are a workaround but this should probably be 2 or 3. @hadley happy to do a PR if you want this bumped up:

https://github.com/r-lib/hugodown/blob/a448558b1beaba8f49a89a3ed071b30079427358/R/hugo-format.R#L24

**Comment by hadley** [comment]
@apreshill For the background around images, I think you just need to update hugodown, since I fixed that this morning.  A PR to change the retina default would be default 😄

**Comment by apreshill** [comment]
I'll close, thanks!
