### ISSUE TITLE
Switch to _site.yaml

### ISSUE THREAD

**Issue by hadley** [r-lib/hugodown#44]
And document https://rmarkdown.rstudio.com/docs/reference/render_site.html#configuration

**Comment by hadley** [comment]
That won't work, so we'll stick with hugodown, and instead adopt what distill does

**Comment by maelle** [comment]
Since I've been reading distill docs I first thought it'd be better to have the same config filename for less confusion but the specific filename is better for (GitHub) code search. :-)
