### ISSUE TITLE
Why not to improve the blogdown instead of  develop a new package ?

### ISSUE THREAD

**Issue by chuxinyuan** [r-lib/hugodown#56]
I found too mang repetitive development ，for example:
do_it() 
do.it()
itDo()
doIt()
just do it, how to choose?
Maybe we just need one, unified syntax, unified framework, integrated functionality.

**Comment by hadley** [comment]
Because it’s a fundamentally different design to blogdown and has rather a different scope (ie just focused on Hugo not other blogging tools). Unfortunately I think it would be a lot more work to try and integrate with the existing blogdown package.
