### ISSUE TITLE
Possible to keep or enter a post title using `use_post()`?

### ISSUE THREAD

**Issue by apreshill** [r-lib/hugodown#57]
Using `hugodown::use_post()`, the title in the post created is always blank (`title: ""`). This is confusing at first if you don't understand posts and slugs. For example, you can knit the post, but if you look at the rendered site's post listing page, you won't be able to click on the post to see it:

<img width="990" alt="Screen Shot 2020-06-15 at 8 34 49 AM" src="https://user-images.githubusercontent.com/12160301/84677145-2c2a4b80-aee3-11ea-96d2-76591c1e048e.png">

If you understand how Hugo works and that the actual link is `post/no-title/` you can of course see the rendered post, but this is likely to be confusing for beginners. Would it be possible to either keep or enter a title into `use_post()`?

I am guessing this is the bit that overwrites the Hugo-ified title from the theme's archetype:

https://github.com/r-lib/hugodown/blob/6812adadd7e887f13cd84772128914edcc6af6b6/R/site-academic.R#L129-L133

**Comment by hadley** [comment]
Ooops, I accidentally made this work only for `use_tidy_post()`.
