### ISSUE TITLE
create_site() for any theme?

### ISSUE THREAD

**Issue by maelle** [r-lib/hugodown#65]
I really like `create_site_academic()` and was wondering whether the experience could be partly extended to any theme: a function that'd take a GitHub repo as input like in blogdown, create the site, and then show messages with bullets of what still needs to be done?

**Comment by maelle** [comment]
(this would be different from having helpers like `create_site_academic()` for more handpicked themes)

**Comment by maelle** [comment]
Instead of

https://github.com/r-lib/hugodown/blob/f7df5654eed3d73b5eeb0f3c646d392441a31f94/R/site-academic.R#L43

There'd be

```r
usethis::ui_todo("Patch the theme for hugodown compatibiliy, see https://hugodown.r-lib.org/articles/config.html")
```

(or see `vignette()` if the installation instructions make sure the vignettes are installed).

The steps before that (downloads, installation) should work for any theme... hosted on GitHub. :thinking:

**Comment by hadley** [comment]
It would be possible, but I'm not really interested in offering that experience in hugodown. There's just too much variation across themes to be able to offer a good experience, so I'd prefer to provide a selected set of helpers for the most useful themes.
