### ISSUE TITLE
is it worth exporting hugo_locate?

### ISSUE THREAD

**Issue by djnavarro** [r-lib/hugodown#68]
I wonder if it would be worth exporting `hugo_locate()`? It's a handy function to use if you're writing a wrapper function that creates sites using a different Hugo theme. At the moment I'm accessing it via `:::` in the slumdown package, but it would be nice to avoid the inevitable warning message on R CMD check:

https://github.com/djnavarro/slumdown/blob/master/R/install_hugodown.R#L16

Alternative options I'm considering:

- I could write a PR to add a `create_site_slum()` function to hugodown instead of having slumdown as a distinct package
- I could mirror `hugo_locate()` and the many internal functions it calls inside slumdown

**Comment by hadley** [comment]
Yeah, it should definitely be exported.
