### ISSUE TITLE
Re-knit all outdated (docs?)

### ISSUE THREAD

**Issue by danmackinlay** [r-lib/hugodown#74]
Perhaps the problem here is me, but I cannot workout hot to re-render all the outdated Rmd files
(this is needed if, e.g. migrating 800 articles from blogdown)

obviously there is `hugodown::site_outdated()` which gives me a list, but then... what?
I can run `knitr::knit(some_path)` but this is blind to the various bits of config and outputs files to the wrong folder.

Before I spend more time trying to work out how to do this myself, could I seek reassurance there is no such function as the imaginary `hugodown::knit_all` that I seek?

**Comment by hadley** [comment]
There's definitely not such a function because it's anti-thetical to the nature of hugodown 😄 But why do you need to rebuild the old blog posts? When I ported the tidyverse blog I just left the existing posts as is.

**Comment by danmackinlay** [comment]
OK, that can be not a thing.

To answer the question though,

1. because the generated HTML for the table of contents is different depending on whether you go through hugodown or blogdown, and it is already tedious yakshaving risk to get TOC looking nice at all, let alone looking nice with two different HTML markup structures to support
2. It is nice to have less HTML lurking around the repo giving me side-eye and cluttering up `grep` results

I understand, of course, that not taking on additional tedious yak-shaving for hugodown maintainers is also a priority, and that there is less lurking HTML side-eye for some folks
