### ISSUE TITLE
No but actually how do I programmatically knit a single hugodown post?

### ISSUE THREAD

**Issue by danmackinlay** [r-lib/hugodown#75]
Oh wizards of hugodown, I beseech thee! No disrespect to RStudio but sometimes I want to knit my hugodown posts from other IDEs, or even from the command-line via `Rscript`.
Currently [the documentation](https://hugodown.r-lib.org/#usage) tells us

>To knit an .Rmd post, you can use the Knit button to knit to the correct output format. You can also use the keyboard shortcut Cmd+Shift+K (Mac) or Ctrl+Shift+K (Windows/Linux).

This unfortunately makes sense only in RStudio and does not give me the information I need to knit the post programatically. I'm presuming it is something obvious such as `knitr::knit("content/notebook/levy_processes.Rmd")` but that does not seem to pick up the right config and renders the markdown output in the current directory rather than next to the post where it belongs.
I expect it is a small change to make this work, but I do not know what it is.
But armed with this information I could add hugodown support to other IDEs (e.g.  [VSCode](https://github.com/TianyiShi2001/rmarkdown-vscode)) and to my own build scripts. And even put it in the documentation of this fine project.

**Comment by hadley** [comment]
Just call `rmarkdown::render()`?

**Comment by danmackinlay** [comment]
🤦 

Thank you.
