### ISSUE TITLE
Fails to deploy when using embracing operator {{}} for tidy eval

### ISSUE THREAD

**Issue by nate-bf** [r-lib/hugodown#77]
Working on a new blog post and kept getting an error when deploying:

`Error: Error building site: "/opt/build/repo/content/post/test_post/index.md:60:38": failed to extract shortcode: template for shortcode "span" not found`

After a bit of experimentation I think this is a problem with how syntax highlighting treats the {{}}. Putting the code below into a hugodown post will reproduce this error .
```
library(tidyverse)

df <- tibble(
  x = 1:4,
  y = c("a", "a", "b", "b")

)

make_groups <- function(df, group_var){
  df <- df %>%
    group_by({{group_var}}) %>%
    summarize(mean = mean(x))
}

df <- df %>%
  make_groups(y)

df
```

**Comment by maelle** [comment]
I proposed a possible fix, replacing the curly braces with the corresponding HTML entities so that Hugo doesn't treat them as a shortcode.

**Comment by natekratzer** [comment]
Thanks for this! I see you've implemented your own tests of this as well, but thought I should mention that I installed this branch and it does work for my blog post as well. And of course say thank you!

(also, this is the same Nate who opened the issue. Accidentally opened it while still signed into my work Github account).
