### ISSUE TITLE
5 second timeout for hugo_start() is too short for large sites

### ISSUE THREAD

**Issue by djnavarro** [r-lib/hugodown#80]
When calling `hugodown::hugo_start()` for my art site I consistently get a timeout error that (I think) is being caused by the 5 second timeout here https://github.com/r-lib/hugodown/blob/e4c67370378ea2addb8933b6b5ee5303617720e5/R/hugo-server.R#L63

Calling `hugo server` from the terminal works fine and once started there I don't get any other errors from any hugodown commands. The main issue is that there are almost 700 large image files in the static folder, and the site takes over 13 seconds to build:

```
                   | EN   
-------------------+------
  Pages            |  48  
  Paginator pages  |   0  
  Non-page files   |  22  
  Static files     | 691  
  Processed images |   0  
  Aliases          |   0  
  Sitemaps         |   1  
  Cleaned          |   0  

Built in 13536 ms
```
It might be an esoteric use case and an easy one to workaround from the terminal, but I thought I'd mention it. 

For reference, in case it is relevant:
 
- the slow-building site is here: https://github.com/djnavarro/art
- the hugo theme is here: https://github.com/djnavarro/hugo-diziet

**Comment by hadley** [comment]
I'd suggest we just bump to 30s. Do you want to do a PR?

**Comment by djnavarro** [comment]
Okay, will do!
