### ISSUE TITLE
failed to realize ...hugo [ENOENT] error

### ISSUE THREAD

**Issue by aziereis** [r-lib/hugodown#95]
Hi! I updated to R 4.0.3 and reinstalled hugodown and now get the following errors that hugo can't be found. (I also tried re-installing this version or installing other hugo versions via hugodown and afterwards locate them or trying to start the server but the problem remains). Thanks for the help!
Restarting R session...
> library(hugodown)
> hugo_version()
[1] "0.66.0"
> hugo_locate(version = "0.66.0")
Fehler: [ENOENT] Failed to realize 'C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/hugo': no such file or directory
> hugo_install(version = "0.66.0")
Finding release
hugo 0.66.0 already installed

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=German_Germany.1252     LC_CTYPE=German_Germany.1252      
> [3] LC_MONETARY=German_Germany.1252    LC_NUMERIC=C                      
> [5] LC_TIME=English_United States.1252
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] hugodown_0.0.0.9000
> 
> loaded via a namespace (and not attached):
>  [1] knitr_1.31        magrittr_2.0.1    rappdirs_0.3.3    R6_2.5.0         
>  [5] rlang_0.4.10      httr_1.4.2        tools_4.0.3       xfun_0.21        
>  [9] cli_2.3.0         htmltools_0.5.1.1 ellipsis_0.3.1    gitcreds_0.1.1   
> [13] yaml_2.2.1        digest_0.6.27     assertthat_0.2.1  tibble_3.0.6     
> [17] lifecycle_0.2.0   crayon_1.4.1      brio_1.1.1        vctrs_0.3.6      
> [21] fs_1.5.0          curl_4.3          glue_1.4.2        evaluate_0.14    
> [25] rmarkdown_2.6     gh_1.2.0          compiler_4.0.3    pillar_1.4.7     
> [29] jsonlite_1.7.2    pkgconfig_2.0.3

**Comment by hadley** [comment]
Can you please try deleting `C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit` and then trying again?

**Comment by aziereis** [comment]
Thanks for your fast reply. I tried it but the error still occurs: 
deleting the folder: 
 > unlink('C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit', recursive = T)
> list.dirs('C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/')
[1] "C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/"
 
so it is actually not there anymode

Restarting R session...

> library(hugodown)
> hugo_version()
[1] "0.66.0"
> hugo_locate(version = "0.66.0")
Fehler: hugo 0.66.0 not installed
i Do you need to call `hugodown::hugo_install('0.66.0')`?
Run `rlang::last_error()` to see where the error occurred.
> hugo_install(version = "0.66.0")
Finding release
Downloading hugo_extended_0.66.0_Windows-64bit.zip...
Installing to C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache...

but still it cannot be located
> hugo_locate(version = "0.66.0")
Fehler: [ENOENT] Failed to realize 'C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/hugo': no such file or directory

if I check the folder incl. the hugo.exe file is there but I don't understand why it cannot access it
> list.dirs('C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/')
[1] "C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/"                                   
[2] "C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache//hugo_extended_0.66.0_Windows_64bit"

**Comment by hadley** [comment]
Can you please give me the output of these lines:

```R
fs::dir_ls("C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/")
fs::file_exists("C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/hugo")
fs::path_real("C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/hugo")
```

**Comment by aziereis** [comment]
Yes, sure. This is the output: 

> fs::dir_ls("C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/")
C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/hugo.exe
C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/LICENSE
C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/README.md

> fs::file_exists("C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/hugo")
C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/hugo 
                                                                                         FALSE 

> fs::path_real("C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/hugo")
Fehler: [ENOENT] Failed to realize 'C:/Users/ziereis/AppData/Local/hugodown/hugodown/Cache/hugo_extended_0.66.0_Windows_64bit/hugo': no such file or directory

**Comment by hadley** [comment]
Hmmmm, so it seems like something to do with the `.exe` extension; I have some vague recollection that I deliberately add them on windows because they were automatically added somewhere.

**Comment by hadley** [comment]
Please try with the latest dev version and let me know if it still doesn't work.
