### ISSUE TITLE
How to use images in blog posts?

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/hugodown#99]
Thanks for this cool package. I could not find a reference to how to embed an image stored somewhere in the repo in a post and standard blogdown approach did not work. 

I put some images in `static` and reference them relative to the location of my post in `content/posts/post-xyz`, i.e. with `../../static/post/post-xyz/...`. Rendering with {knitr} works. But then, `hugodown::hugo_start()` renders md to html, and the paths are wrong (I believe because the working directory is a different one) and images are not displayed. I manually changed the paths in the `.md` after knitting to be relative to the root (`/post/post-xyz/...`), as all static content is placed there, and then they were displayed correctly, but that's a bit of a hack. 

I was not sure if I hit a limitation described in the README, but I felt probably it's something else:

> It does not currently support within page cross-references for figures, tables, and equations.

**Comment by maelle** [comment]
How are your posts organized? The images could be in the same folder as the post (e.g. `content/post-xyz/` where the post itself is index.Rmd/index.md).

From a rapid look it does not seem explicitely documented e.g. in https://hugodown.r-lib.org/reference/use_post.html. :thinking: 

Example https://github.com/tidyverse/tidyverse.org/tree/master/content/blog/workflowsets-0-0-1

Also relevant https://alison.rbind.io/post/2019-02-21-hugo-page-bundles/ (to read about leaf bundles)

**Comment by hadley** [comment]
I don't know if I ever tested this, but basically the only way I ever insert images into Rmds is `knitr::include_graphics()` so that's the thing I'm most likely to have tested.

**Comment by lorenzwalthert** [comment]
Thanks to both, I mimicked what was done in the {workflowsets} and it worked. I previously also put a folder with the same name as the blog post in the `content/post` and then the figure there, but it got wiped out for some reason during the build process. Putting both post and images in (subfolders of) `content/post/name-of-post` did the job.
